web:
  image: nginx:latest
  ports:
    - "80:80"
  volumes:
    - .:/code
    - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
  build: .
  volumes: 
    - .:/code
  links:
    - mysql

mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment: 
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  volumes:
    - "./docker/mysql/scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
    - "./docker/mysql/scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - mysql:db
  ports:
    - "8082:80"
  environment:
    - PMA_USER=${PMA_USER}
    - PMA_PASSWORD=${PMA_PASSWORD}
    - PHP_UPLOAD_MAX_FILESIZE=100MB
